### PR TITLE
Analogue mic processing improvements (fixes #167)

### LINKED ISSUE #167: Soundreactive wled noise issue
**Describe the bug**

Hello I'm making a diy nanoleaf with about 565 neopixels, a 5v 20a power supply, esp32 dev and a max 4466 electret mic. The esp boot cycles on power up but sometimes turns on fine. But when I turn on a music effect the leds bounce around in complete silence. Decreasing the gain on the max4466 does solve this issue but it becomes too un sensitive. Pls help
**To Reproduce**
Squinch:19 gain:5 ADC:34 
Taped to my TV's speaker
Depth: halfway
Gain on mic board: unknown

**Expected behavior**
The whole strip is off at silence’’
Reacts to music that is a bit faint too*
Reacts to bass 
Reacts to bass in rapid succession
Maybe reacting to lyrics as well*
Maybe react to speech in the bg*
* = optional but will be cool if possible
’’ = if possible but needed a bit more than the *'s

**WLED version**
Esp32 dev
 - Version   latest
 - Format   web browser flash
**Additional context**
I'd maybe also use line in but haven't tested it out yet. If I opt using line in, how do I play music on speaker as well as headphone jack?

### PR DESCRIPTION
**Pull request by softhack007**
initial commit, work in progress
* request 16bit samples from I2S
* no start/stop of ADC processing, to avoid ugly artefacts
* I2S buffer size increased
* samples go into FFT as-is, no adjustments to remove DC or take absolute values
* small improvement to FFT: DCRemove, different windowing function
* avoid several "rounds" of abs(), smoothing and DC removal

Comments welcome :-)

Update: found out that ADC samples are 0...4096(unsigned), while all digital mics deliver at least 16bit (signed, int16). Will add some code tomorrow, to "up-scale" ADC samples so they are in the same range as delivered by digital ones.

### CODE REVIEW

**Comment by atuline** [comment]
The hero we need to sort out my post processing abominations.

**Comment by softhack007** [comment]
Thanks for the flowers :smile: a bit more fixing will come soon.

**Comment by FHeilmann** [comment]
Out of curiosity, which hardware combinations was this tested with?

**Comment by softhack007** [comment]
Hi Florian,
It's still work-in-progress, based on my personal fixes that "work for me" since a few weeks now. 

I am using a MAX4466 mic, with "Lolin32 lite" board (ESP32, however not based on WROOM/WROVER).
While I'm very confident about changes in sound processing, the change to always request 16bit samples from the I2S driver are a bit experimental. Tell me if this does not work for some digital mic - I can revert that part very easily.

**Comment by atuline** [comment]
> Thanks for the flowers 😄 a bit more fixing will come soon.

Don't forget to get on Discord to discuss. Here is a liknk:

https://discord.gg/vTAprvc5

Haribo is the person you need to talk do. There's now several I2S microphones supported, and I believe he's balancing between the SR functionality and conmpatibility of each.

**Pull request merged**
