### PR TITLE
Added DigitalMic checkbox to sound-settings

### PR DESCRIPTION
**Pull request by GrumpyMeow**
Hi,
A simple changeset which adds a checkbox on the Sound Settings page to select either a analog or digital microphone.
The automatic digital-microphone detection doesn't always work correctly.

### CODE REVIEW

**Comment by atuline** [comment]
Could you elaborate on the digital-microphone testing issues? Basically, the I2S microphones are VERY sensitive if they are working, and they sometimes don't work as a result of various hardware issues, unrelated to the code.

The code checks for any non-zero output from them and has worked for me.

**Comment by GrumpyMeow** [comment]
Hi Andrew,

I know how the code checks for the digitalMic and expected it to work. On one of my ESP32 it does work every time. On another ESP32 it didn't. The WLed effects would be activated, while it was complete silence.

I also noticed in the discord channel that people were having a hard time with the INMP441 microphone.

So these are the reasons for me creating this PR. It at least gives an ondication which microphone is detected.

Ofcourse no problem if you think it's best to not merge this PR.

**Comment by atuline** [comment]
I'll ask the other folks on the team, and see what they think. Would be nice to get some visual feedback on whether any mic, digital or analog is attached and to be able to select the mic.

**Comment by THATDONFC** [comment]
I think this idea is valid. Have you tested the functionality with an esp32 build with digital mic? If not, could you please do so and report your findings?

**Comment by GrumpyMeow** [comment]
Hi Thatdonfc,

Yes. I've got two ESP32+INMP441 and tested this change on them. I think this is a change which (hopefully) will be extended with more options in the future. For instance: selecting input pin, etc.

**Comment by netmindz** [comment]
Can you update your merge request to update to resolve the conflict?

**Comment by FHeilmann** [comment]
With the recent changes by THATDONFC and myself, I the functionality of this PR has been added to WLED-SR. Anything else that you feel is still missing? @GrumpyMeow ?

**Comment by THATDONFC** [comment]
As @FHeilmann stated, this functionality is now included in WLED-SR. Closing this PR

**Pull request closed without merging**
