### PR TITLE
Additional guard delay after i2s_driver_uninstall

### PR DESCRIPTION
**Pull request by phonec**
Solving the problem of initialization of an I2S peripheral, in which it may be in an indeterminate state after a soft reset, in which the analog microphone does not work.

### CODE REVIEW

**Comment by phonec** [comment]
unfortunately this solution is only for a specific unit of the device, I tested it on another board after a soft reset, the analog microphone stopped working :(

**Comment by phonec** [comment]
there is another option: to use the registers writing sequence from the bootloader_random_disable() function of the esp-idf component bootloader_support , this option also gave good results, but obviously you need to test for a long time.

**Comment by softhack007** [comment]
Well, I'm not really good at fiddling around with registers. Let's leave it as-is for now. If the additional change works for you for some time, you could make a second PR.  That one also needs to be tested for not causing negative consequences on other drivers (i.e. non-ADC). 

Maybe place the register writing sequnce into `I2SAdcSource::initialize()`, and guard it with an extra `#ifdef` to check the ESP-IDF version, like `#if ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(4, 0, 0)` so it does not cause problems on other MCUs, or on newer IDF versions. 

background: I want to keep the source code similar between SR WLED and the MoonModules fork. In MoonModules, we already support ESP32-S3 which needs IDF v4.4.1 or above.

**Comment by phonec** [comment]
Thanks for the details, I will do as you ask, I will need more time to investigate this problem

**Comment by Funkelfetisch** [comment]
I found this thread while looking for esp32-s3 in this repo.

@softhack007 is there a SR fork ready for esp32-s3 anywhere? I can't find it but need it desperately.

**Pull request merged**
